### ISSUE TITLE
OSError: Can't load config for 'stabilityai/sd-vae-ft-mse'

### ISSUE THREAD

**Issue by jeffreyrobeson** [chenshine1/oms-Diffusion#7]
Traceback (most recent call last):
  File "E:\software\oms-Diffusion\gradio_generate.py", line 17, in <module>
    vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse").to(dtype=torch.float16)
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: Can't load config for 'stabilityai/sd-vae-ft-mse'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/sd-vae-ft-mse' is the correct path to a directory containing a config.json file

**Comment by chenshine1** [comment]
make sure you can connect to huggingface or download the model at first from other mirror site.
